# Generated by Django 4.2.16 on 2024-10-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscription',
            table='list_subscription',
        ),
    ]
